name: pyqt
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - openssl=3.0.16
  - python=3.10.16
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - ansitable==0.11.4
      - asttokens==3.0.0
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - certifi==2025.1.31
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cmake==4.0.3
      - colorama==0.4.6
      - colored==2.3.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - dash==3.0.2
      - decorator==5.2.1
      - distlib==0.3.9
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flask==3.0.3
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - identify==2.6.9
      - idna==3.10
      - importlib-metadata==8.6.1
      - ipython==8.35.0
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - machinevision-toolbox-python==1.0.1
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - mvtb-data==1.5
      - narwhals==1.34.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netft==2.0.1
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numpy==1.26.4
      - open3d==0.19.0
      - opencv-contrib-python==4.5.4.60
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pgraph-python==0.6.3
      - pillow==11.1.0
      - pip==25.1.1
      - platformdirs==4.3.7
      - plotly==6.0.1
      - pre-commit==4.2.0
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyads==3.5.0
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - pyqtchart==5.15.7
      - pyqtchart-qt5==5.15.2
      - pyrealsense2==2.55.1.6486
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywin32==310
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - retrying==1.3.4
      - rpds-py==0.24.0
      - scipy==1.15.2
      - seaborn==0.13.2
      - setuptools==80.9.0
      - six==1.17.0
      - soupsieve==2.7
      - spatialmath-python==1.1.14
      - stack-data==0.6.3
      - sympy==1.13.1
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.13.1
      - tzdata==2025.2
      - ultralytics==8.3.105
      - ultralytics-thop==2.0.14
      - urllib3==2.3.0
      - virtualenv==20.30.0
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - xlsxwriter==3.2.9
      - zipp==3.21.0
prefix: C:\Users\sys314\.conda\envs\pyqt
